version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemon
    volumes:
      # - ./mongo:/data/db si haces build puro funciona pero con -d no
      - /mongo/data:/data/db
